name: 'VirusTotal Action'
description: 'Scan Files using the VirusTotal API'
author: 'Shane'

inputs:
  chrome:
    description: 'Chrome Archive Location'
    required: false
  firefox:
    description: 'Firefox Archive Location'
    required: false

#outputs:
#  time:
#    description: 'The time we greeted you'

runs:
  using: 'node20'
  main: 'dist/index.js'
