name: 'VirusTotal Action'
description: 'Scan Files using the VirusTotal API'
author: 'Shane'

inputs:
    github_token:
        description: 'GitHub Token from secrets.GITHUB_TOKEN'
        required: true

#outputs:
#  time:
#    description: 'The time we greeted you'

runs:
    using: 'node20'
    main: 'index.js'
